apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: gradle-
spec:
  entrypoint: pipeline
  templates:
    - name: pipeline
      steps:
        - - name: build
            templateRef:
              name: gradle-task-template
              template: gradle-task
            arguments:
              parameters:
                - name: task-name
                  value: "build"
                - name: gradle-opts
                  value: "--info"
        - - name: test
            templateRef:
              name: gradle-task-template
              template: gradle-task
            arguments:
              parameters:
                - name: task-name
                  value: "test"
                - name: gradle-opts
                  value: "--info"