apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-template
spec:
  entrypoint: build
  templates:
    - name: build
      inputs:
        parameters:
          - name: capture-output
            value: "true"
      container:
        image: alpine
        command:
          - sh
          - c
        args:
          -  "echo 'running build' | tee /tmp/build_result.txt"
      outputs:
        artifacts:
          - name: build-output
            path: /tmp/build_result.txt
            optional: "{{inputs.parameters.capture-output}}"